import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import LandingLayout from "@/components/Layouts/LandingLayout";
import { SecondaryBtn } from "@/components/shared/Buttons";
import HomePageComp from "@/components/pagesComp/HomePageComp";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />

        <title>
          CareerAI | Online Resume Builder - Create Professional Resumes
          Instantly
        </title>
        <meta
          name="title"
          content="CareerAI | Online Resume Builder - Create Professional Resumes"
        />
        <meta
          name="description"
          content="Build professional resumes quickly and easily with our online resume builder. Choose from customizable templates, enter your details, and generate a polished CV. Download in PDF format. Get started today!"
        />

        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.careerai.io/" />
        <meta
          property="og:title"
          content="CareerAI | Online Resume Builder - Create Professional Resumes"
        />
        <meta
          property="og:description"
          content="Build professional resumes quickly and easily with our online resume builder. Choose from customizable templates, enter your details, and generate a polished CV. Download in PDF format. Get started today!"
        />
        <meta
          property="og:image"
          content="https://www.careerai.io/images/seo.png"
        />

        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="https://www.careerai.io/" />
        <meta
          property="twitter:title"
          content="CareerAI | Online Resume Builder - Create Professional Resumes"
        />
        <meta
          property="twitter:description"
          content="Build professional resumes quickly and easily with our online resume builder. Choose from customizable templates, enter your details, and generate a polished CV. Download in PDF format. Get started today!"
        />
        <meta
          property="twitter:image"
          content="https://www.careerai.io/images/seo.png"
        />
      </Head>
      <LandingLayout>
        <HomePageComp />
      </LandingLayout>
    </>
  );
}
